name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: TShockPrometheus/bin/**/*
    - name: Prepare Release Artifact
      run: |
        cd TShockPrometheus\bin\Release\net6.0\
        7z a ..\..\..\..\TShockPrometheus-${{ steps.tagName.outputs.tag }}.zip TShockPrometheus.dll System.ValueTuple.dll Prometheus.NetStandard.dll
        cd ..\..\..\..
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
    - name: Upload Release Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: TShockPrometheus-${{ steps.tagName.outputs.tag }}.zip
        asset_name: TShockPrometheus-${{ steps.tagName.outputs.tag }}.zip
        asset_content_type: application/zip
